name: Localization

on:
  push:
    branches:
    - localization

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set Node.js 10.13.0
      uses: actions/setup-node@master
      with:
        node-version: 10.13.0

    - name: Install dependencies
      run: npm install axios@^0.19.2 @actions/github@^2.1.0

    - name: Run automation
      run: node ./.github/workflows/scripts/localization.js
      env:
        CROWDIN_KEY: ${{secrets.CROWDIN_KEY}}
        CROWDIN_PROJECT_NAME: ${{secrets.CROWDIN_PROJECT_NAME}}
        SKIP_DOWNLOAD: ${{secrets.SKIP_DOWNLOAD}}
        SKIP_UPLOAD: ${{secrets.SKIP_DOWNLOAD}}