name: Localization

on:
  push:
    branches:
    - localization

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set Node.js 10.13.0
      uses: actions/setup-node@master
      with:
        node-version: 10.13.0

    - name: Install dependencies
      run: npm install

    - name: Run automation
      run: node ./scripts/localization.js